#!/bin/bash

INPUT=example.txt
OUTPUT=example.json
LINE_CURRENT=0
LINE_TOTAL=$(cat $INPUT | wc -l)

exec > $OUTPUT
echo "{
        \"data\":[
"
while IFS=" " read -r V1 V2 V3
do
        LINE_CURRENT=$(($LINE_CURRENT + 1))
        if [ $LINE_CURRENT -lt $LINE_TOTAL ] ; then
                echo -e "       { \"{#HOSTNAME}\":\""$V1"\", \"{#IP}\":\""$V2"\", \"{#PORT}\":\""$V3"\" },"
        else
                echo -e "       { \"{#HOSTNAME}\":\""$V1"\", \"{#IP}\":\""$V2"\", \"{#PORT}\":\""$V3"\" }"
        fi
done < $INPUT
echo "
        ]
}"
